---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь должен иметь возможность переключить язык интерфейса
  - Сайт должен иметь локализацию (перевод) на русский и английский языки

non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Одинаковые стили кнопок, шрифтов, цветов на всех страницах
  - Пользователь не должен "теряться" при переходе между разделами
  - Оформление заказа не должно требовать 10 шагов.
  - Если пользователь дважды нажал "Оплатить", не должно создаваться два одинаковых заказа.
  - Возврат не должен сбрасывать корзину или введенные данные.
  - Страницы должны открываться за 2-3 секунды даже при медленном интернете.
  - Если что-то сломалось, админ должен увидеть это в логах.
  - Если пользователь попал на битую ссылку, его нужно перенаправить.
  - Если оплата через PayPal не работает, должна быть альтернатива.
  - При ошибке API сайт не должен "лагать" 10 секунд.